# Generated by Django 5.1.6 on 2025-02-24 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_apimodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='sender',
            field=models.CharField(default='You', max_length=100),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
