# Generated by Django 5.1.6 on 2025-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_apimodel_sender_alter_apimodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
