# Generated by Django 5.1.6 on 2025-02-25 13:00

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_apimodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=apis.models.upload_to_overwrite),
        ),
    ]
