# Generated by Django 5.1.6 on 2025-02-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_apimodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
