# Generated by Django 5.1.6 on 2025-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_apimodel_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='upload_to_overwrite')),
            ],
        ),
        migrations.RemoveField(
            model_name='apimodel',
            name='pdf',
        ),
    ]
