# Generated by Django 5.1.6 on 2025-02-25 17:41

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_apimodelfile_remove_apimodel_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodelfile',
            name='pdf',
            field=models.FileField(upload_to=apis.models.upload_to_overwrite),
        ),
    ]
