# Generated by Django 5.1.6 on 2025-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_apimodelfile_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='toggle',
            field=models.BooleanField(default=False),
        ),
    ]
